### ISSUE TITLE
[FEAT]Feature/hyo branch 작업

### ISSUE THREAD

**Issue by kimkeonhyo** [Kakao-X-Goorm-DEEP-DIVE-course/Catch-Goorm#1]
## Background
- Django & docker-compose를 이용한 팀미션 활동 진행

## Todo
- [x] Develop branch Pull을 이용하여 가저오기
- [x] Django - docker - DB(mysql) 연결 및 동작하기
- [x] CSS 및 HTML 수정
- [x] github repository push_branch feature/hyo

##See also
- [현민님 블로그](https://velog.io/@khm0930/%EC%BB%A8%ED%85%8C%EC%9D%B4%EB%84%88%ED%99%98%EA%B2%BD%EC%97%90%EC%84%9C-%EC%8B%A4%ED%96%89%ED%95%98%EB%8A%94-%EC%82%AC%EC%9A%A9%EC%9E%90-CRUD%EA%B8%B0%EB%8A%A5-%EA%B5%AC%ED%98%84-DjangoNginxmySQL-%ED%99%98%EA%B2%BD%EC%84%B8%ED%8C%85)

**Comment by kimkeonhyo** [comment]
css로 레이아웃 짜는게 어려웠다
