### ISSUE TITLE
[FEAT] Feature/hyunmin 브랜치 작업

### ISSUE THREAD

**Issue by khm0930** [Kakao-X-Goorm-DEEP-DIVE-course/Catch-Goorm#2]
## Background
- Django & docker-compose를 이용한 팀미션 활동 진행
## Todo
- [x] develop 브랜치에 기본 코드 push
- [x] 나만의 작업 공간 hyunmin_feature 브랜치 생성 후 우선 push 해놓기
- [x] 유효성 검사 , 비밀번호랑 이름만 변경되게 바꾸기

##See also
- GPT
