### ISSUE TITLE
[FEAT]Feature_YB Issue up

### ISSUE THREAD

**Issue by TigerLee0225** [Kakao-X-Goorm-DEEP-DIVE-course/Catch-Goorm#9]
## Background
- youngbum_feature branch를 더 이상 사용하지 않습니다. 개인 Repo를 현 Repo에서 fork하여 사용 중입니다.
- 보안 관련 .env의 이슈가 있어 .gitignore 파일을 수정해야 합니다. .env 파일은 민감한 정보를 가지고 있어서 git repo에 push되면 안됩니다.
- 그 외 기타 minor changes

## Todo
- [x] youngbum_feature branch 삭제
- [x] .gitignore 파일에 *env를 추가
- [x] docker-compose.yml 파일에 줄바꿈이 1개 추가되었습니다. 마이너한 수정
- [x] nginx/default.conf 파일을 제가 구형 버전을 갖고 있어서 최근 pull한 버전으로 수정하였습니다. 중간에 merge conflict가 생겨서 매뉴얼 수정했습니다.

##See also
- https://velog.io/@de-quei/Github%EC%97%90-.env%ED%8C%8C%EC%9D%BC%EC%9D%84-push%ED%96%88%EC%9D%84-%EB%95%8C

**Comment by TigerLee0225** [comment]
문제를 모두 해결했습니다!
